language: node_js

node_js:
  - '6'

before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn

cache:
  directories:
    - "$HOME/.yarn-cache"

notifications:
  slack:
    secure: H5nHVkkfnLFYDGrZy+5Zo49LXnzFn0NPgFX1hXnV3rd4lgnky5wiFv3zSIv25Aj+TOTyrIKivYP+XiT4fZkFcV7OvfmVngTjXM4CLCOVJVN8puMbfRmRkrlvn+QY7MHanDAKsCfMTBvQ9Ajt1ntZS4rzTSeB/t4GHocpWSyLTfcSFxCXS6O1oJz6SQSnuwNbBuUWAIZ4nhGVa6Tgm4/PHdmDw1mGIgC+drsqizlX9heL8AB/WUHUSmdOwt6An4IYAYFU7LSqmwEHZ0BUzgkuPH81G2b0wlMyFBOV+MRaxLf1e0/FJZKLpZHuxD5RkN2x1XIdVMISU6VlUtBgZ7xzlx++M7nAOoa24+bBtzhzo6jr4nVtn4rIgJa35Db+rnCok6kAaonrsIpdgpzGKKBKd4KgOrTn/DHuzA6HvXg6sdr3gzabIDj3Tx878VrPktpCUtMLe8/cgWAaGcLI1W9+b/TeKIOqPDjUK4y7/0K/H3OffFyDvq2Yuze44BSS+vuS39Ahy7m6ZhhcOKGoC0Ev5GBkdHYZgU30rOjR29EPE6eHVsZy1vfpV2GV8SgkJ0Ka6Yc6a0G8HE9TuBxkA2xUzij7DyxJFdI/QP5zWxiMqGtSCCdS9wj+hvmhEpcM7RcllQm+YPK6dpRIg0/NlPUF+Ip1JQmvnaMezUv3J96jjak=
